export const CHANGE_INPUT_VALUE = 'change_input_value'
export const ADD_TODO_ITEM = 'add_todo_item'
export const DELETE_TODO_ITEM = 'delete_todo_item'
export const INIT_LIST_DATA = 'init_list_data'
export const GTE_INIT_LIST_DATA = 'get_init_list_data'